### ISSUE TITLE
Status Update (2022-09-08)

### ISSUE THREAD

**Issue by alexbevi** [alexbevi/developer-roadmap#2]
# Checkout and Run
```bash
git clone https://github.com/alexbevi/developer-roadmap.git
git checkout mongodb
npm run dev
```
This should spawn the dev server on http://localhost:3000

# Preview

![image](https://user-images.githubusercontent.com/135803/189162729-196364ec-618f-44aa-9fa8-d701a322214e.png)

# TODO

- [ ] Validate Layout
- [ ] Restructure layout based on feedback
- [ ] Tag layout elements for interactivity
- [ ] Engage content collaborators to populate markdown files
